name: Download Grok-1 Model Weights

on: [push]

jobs:
  download-weights:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Clone Grok-1 Repository
      run: git clone https://github.com/xai-org/grok-1.git && cd grok-1
    - name: Install huggingface_hub
      run: pip install huggingface_hub[hf_transfer]
    - name: Download Grok-1 Model Weights
      run: huggingface-cli download xai-org/grok-1 --repo-type model --include ckpt-0/* --local-dir checkpoints --local-dir-use-symlinks False
