name: Download Grok-1 Model Weights and Test

on: [push]

env:
  GROK_1_WEIGHTS_URL: https://huggingface.co/grok-1/weights/download
  GROK_1_WEIGHTS_FILE: grok-1-weights.tar.gz

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Download Grok-1 Model Weights
      run: |
        wget -O $GROK_1_WEIGHTS_FILE $GROK_1_WEIGHTS_URL || { echo "Download failed"; exit 1; }
        tar -xzvf $GROK_1_WEIGHTS_FILE -C checkpoints/ || { echo "Extraction failed"; exit 1; }

    - name: Run Tests with pytest
      run: pytest
